### ISSUE TITLE
Mipmap byte count exceeds maximum size when converting .tex files

### ISSUE THREAD

**Issue by ykozxy** [notscuffed/repkg#12]
Hi there, 

When I tried to convert a large .tex file (about 83 MB) using the program, it throws an error and skips that file. 

```
* Extracting: materials/File Nov 08, 17 51 21.tex
* Reading: materials/File Nov 08, 17 51 21.tex
Failed to read texture
RePKG.Application.Exceptions.UnsafeTexException: Unsafe TEX detected, reason: Mipmap byte count exceeds maximum size: 64223148/50000000
   at RePKG.Application.Texture.TexImageReader.ReadBytes(BinaryReader reader)
   at RePKG.Application.Texture.TexImageReader.ReadMipmapV2And3(BinaryReader reader)
   at RePKG.Application.Texture.TexImageReader.ReadFrom(BinaryReader reader, TexImageContainer container, TexFormat texFormat)
   at RePKG.Application.Texture.TexImageContainerReader.ReadFrom(BinaryReader reader, TexFormat texFormat)
   at RePKG.Application.Texture.TexReader.ReadFrom(BinaryReader reader)
   at RePKG.Command.Extract.LoadTex(Byte[] bytes, String name)
```

Is there a way to avoid this maximum byte detection? Thanks for any response.

**Comment by notscuffed** [comment]
Hello,

I've increased the maximum mipmap size to 250MB from 50MB.

You can download the latest version here:
https://github.com/notscuffed/repkg/releases/tag/v0.2.2-alpha

Let me know if that fixued ur issue.

**Comment by ykozxy** [comment]
Thanks! The latest version works for me ;)
