### ISSUE TITLE
Failed to write texture

### ISSUE THREAD

**Issue by slavikfoxy** [notscuffed/repkg#50]
Command repkg extract -t -s "C:\TEX" v. 0.3.1_alpha
file 2560x1600.tex
https://steamcommunity.com/sharedfiles/filedetails/?id=3223879712
error:
C:\Program Files (x86)\Steam\steamapps\workshop\content\RePKG\RePKG v0.3.1-alpha>repkg extract -t -s "C:\TEX"
* Reading: C:\TEX\2560x1600.tex
Failed to write texture
System.InvalidOperationException: Expected mp4 magic header
   at RePKG.Application.Texture.TexToImageConverter.ConvertToImage(ITex tex)
   at RePKG.Command.Extract.ConvertToImageAndSave(ITex tex, String path, Boolean overwrite)
   at RePKG.Command.Extract.ExtractTexDirectory(DirectoryInfo directoryInfo)
Done

C:\Program Files (x86)\Steam\steamapps\workshop\content\RePKG\RePKG v0.3.1-alpha>

**Comment by notscuffed** [comment]
Fixed in latest version
