### ISSUE TITLE
There is no exe file to open

### ISSUE THREAD

**Issue by Dogge59** [notscuffed/repkg#6]
I dont know how to open the console window because i dont find any files to open

**Comment by notscuffed** [comment]
You probably downloaded the source, not the executable.

You can download it [here](https://github.com/notscuffed/repkg/releases/download/v0.1.5-alpha/RePKG.exe)

**Comment by Dogge59** [comment]
Now i can open and run the exe but I get this message:
C:\Users\username\Desktop\RePKG.exe extract -t C:\Users\username\Desktop\filename.tex
* Decompiling: C:\Users\username\Desktop\filename.tex
Failed to decompile
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\username\output\filename.jpg'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at RePKG.Texture.Tex.DecompileAndSave(String path, Boolean overwrite)
   at RePKG.Command.Extract.ExtractFile(FileInfo fileInfo)
Done

I don't know how to fix this issue

**Comment by notscuffed** [comment]
For some reason it seems like it failed to create output directory, try creating folder named output on your desktop and try again

**Comment by notscuffed** [comment]
I've updated the program, I forgot to make it create output directory while extracting single tex file.

You can download the new version [here](https://github.com/notscuffed/repkg/releases/download/v0.1.6-alpha/RePKG.exe)

**Comment by Dogge59** [comment]
Now it works flawlessly, thank you
